apps/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.profile_view, name="profile"),
    path("edit/", views.profile_edit_view, name="profile-edit"),
    path('password/', views.profile_password_change_view, name='profile-password-change'),
    path('email/', views.profile_email_change_view, name='profile-email-change'),
    path('emailverify/', views.profile_email_verify_view, name='profile-email-verify'),
    path('delete/', views.profile_delete_view, name='profile-delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.users.views import profile_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('account/', include('allauth.urls')),
    path('', include('apps.core.urls')),
    path('profile/', include('apps.users.urls')),
    path('@<username>/', profile_view, name='profile'),
    path("__reload__/", include("django_browser_reload.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.templatetags.static import static
from django.core.validators import RegexValidator
from django.utils.translation import gettext_lazy as _

class Profile(models.Model):
    GENDER_CHOICES = [
        ('M', _('Male')),
        ('F', _('Female')),
        ('O', _('Other')),
        ('P', _('Prefer not to say')),
    ]

    THEME_CHOICES = [
        ('light', _('Light')),
        ('dark', _('Dark')),
        ('system', _('System')),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name=_('User'))
    avatar = models.ImageField(
        upload_to='avatars/',
        null=True,
        blank=True,
        verbose_name=_('Avatar')
    )
    gender = models.CharField(
        max_length=1,
        choices=GENDER_CHOICES,
        null=True,
        blank=True,
        verbose_name=_('Gender')
    )
    birthday = models.DateField(
        null=True,
        blank=True,
        verbose_name=_('Birthday')
    )
    bio = models.TextField(
        null=True,
        blank=True,
        verbose_name=_('Bio')
    )
    phone_number = models.CharField(
        max_length=15,
        null=True,
        blank=True,
        validators=[RegexValidator(
            regex=r'^\+?1?\d{9,15}$',
            message=_("Enter a valid phone number.")
        )],
        verbose_name=_('Phone number')
    )

    def __str__(self):
        return f"{self.user.username}'s Profile"

    @property
    def avatarDisplay(self):
        try:
            return self.avatar.url
        except ValueError:
            return static('images/avatar.svg')

    @property
    def fullName(self):
        return f"{self.user.first_name} {self.user.last_name}".strip() or self.user.username

apps/users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from allauth.account.forms import SignupForm
    
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input', 'placeholder': '...'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input', 'placeholder': '...'}),
        }

    # capitalize first and last names
    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name', '')
        return first_name.title()
    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name', '')
        return last_name.title()

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']
        widgets = {
            'avatar': forms.ClearableFileInput(attrs={'id': 'avatarInput', 'class': 'hidden'}),
            'gender': forms.Select(choices=Profile.GENDER_CHOICES, attrs={'class': 'form-input w-full bg-transparent'}),
            'birthday': forms.DateInput(attrs={'type': 'date', 'class': 'form-input'}),
            'bio': forms.Textarea(attrs={'rows': 4, 'class': 'form-input', 'placeholder': '...', 'maxlength': 180, 'style': 'resize: none; font-size: 1rem;'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-input', 'placeholder': '...'}),
        }

class EmailForm(forms.ModelForm):
    email = forms.EmailField(
        max_length=255,
        required=True,
        widget=forms.EmailInput(attrs={'class': 'input', 'placeholder': 'New Email'}),
    )

    class Meta:
        model = User
        fields = ["email"]

    def clean_email(self):
        email = self.cleaned_data["email"].strip().lower()

        # Check if email is already in use by another user
        if User.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("This email is already in use.")

        return email

class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=30, required=True, label="First Name")
    last_name = forms.CharField(max_length=30, required=True, label="Last Name")

    def save(self, request):
        user = super().save(request)
        user.first_name = self.cleaned_data["first_name"].title()
        user.last_name = self.cleaned_data["last_name"].title()
        user.save()
        return user

apps/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from allauth.account.utils import send_email_confirmation
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.contrib import messages
from django.utils.translation import gettext as _
from .forms import *

def profile_view(request, username=None):
    if username:
        profile = get_object_or_404(User, username=username).profile
    else:
        try:
            profile = request.user.profile
        except:
            return redirect('account_login')
    return render(request, 'profile.html', {'profile': profile})

@login_required
def profile_edit_view(request):
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, _('Profile updated successfully!'))
            return redirect('profile')
        else:
            # Add form errors to messages
            for field, errors in user_form.errors.items():
                for error in errors:
                    messages.error(request, _("User %(field)s: %(error)s") % {'field': field, 'error': error})
            for field, errors in profile_form.errors.items():
                for error in errors:
                    messages.error(request, _("Profile %(field)s: %(error)s") % {'field': field, 'error': error})
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)

    return render(request, 'profile_edit.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponse
from django.urls import reverse

@login_required
def profile_password_change_view(request):
    form = PasswordChangeForm(request.user, request.POST or None)

    if request.htmx:
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, request.user)
            messages.success(request, _('Password updated successfully!'))
            response = HttpResponse()
            response["HX-Redirect"] = reverse("settings")
            return response
        else:
            return render(request, 'partials/password_errors.html', {'form': form})

    elif request.method == "POST":
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, request.user)
            messages.success(request, _('Password changed!'))
            return redirect('settings')

    return render(request, 'change_password.html', {'form': form})

@login_required
def profile_email_change_view(request):
    user = request.user
    form = EmailForm(instance=user)

    if request.method == "POST":
        form = EmailForm(request.POST, instance=user)

        if form.is_valid():
            email = form.cleaned_data["email"]

            if User.objects.filter(email=email).exclude(pk=user.pk).exists():
                messages.warning(request, _("%(email)s is already in use.") % {'email': email})
            else:
                form.save()
                send_email_confirmation(request, user)

            return redirect("profile-edit")

        messages.error(request, _("Invalid email. Please try again."))

    return render(request, "email.html", {"form": form})

@login_required
def profile_delete_view(request):
    user = request.user
    if request.method == 'POST':
        logout(request)
        user.delete()
        messages.success(request, _('Account deleted!'))
        return redirect('home')

    return render(request, 'account_delete.html')

@login_required
def profile_email_verify_view(request):
    send_email_confirmation(request, request.user)
    return redirect('profile-edit')

apps/users/templates/change_password.html
{% extends 'layouts/form_layout.html' %}
{% load i18n %}

{% block label %}{% trans "Change Password" %}{% endblock %}

{% block buttons %}
    <button onclick=" document.getElementById('changePasswordForm').submit()" id="saveButton" class="button button-primary button-disabled" type="submit">{% trans "Change Password" %}</button>
    <a href="{% url 'settings' %}" class="button">{% trans "Cancel" %}</a>
{% endblock %}

{% block form_content %}
<div class="flex flex-col items-center justify-center">
    <form
        class=""
        id="changePasswordForm"
        action="{% url 'profile-password-change' %}"
        method="post">
        {% csrf_token %}

        <i class="material-symbols-outlined text-5xl py-10 w-full text-center">lock</i>

        <!-- Current Password -->
        <div class="flex items-center justify-between gap-4">
            <h1 class="text-right flex-1">{% trans "Current Password" %}</h1>
            <input id="id_old_password" type="password" name="old_password" class="input w-[360px]" autofocus required>
        </div>
        {% if form.old_password.errors %}
            <p class="text-red-500 text-xs w-[360px] p-2 ml-auto">{{ form.old_password.errors.0 }}</p>
        {% else %}
            <div class="py-4"></div>
        {% endif %}

        <!-- New Password -->
        <div class="flex items-center justify-between gap-4">
            <h1 class="text-right flex-1">{% trans "New Password" %}</h1>
            <input type="password" name="new_password1" class="input w-[360px]" required>
        </div>
        {% if form.new_password1.errors %}
            <p class="text-red-500 text-xs w-[360px] p-2 ml-auto">{{ form.new_password1.errors.0 }}</p>
        {% else %}
            <div class="py-4"></div>
        {% endif %}

        <!-- Confirm Password -->
        <div class="flex items-center justify-between gap-4">
            <h1 class="text-right flex-1">{% trans "Verify Password" %}</h1>
            <input type="password" name="new_password2" class="input w-[360px]" required>
        </div>
        {% if form.new_password2.errors %}
            <p class="text-red-500 text-xs w-[360px] p-2 ml-auto">{{ form.new_password2.errors.0 }}</p>
        {% endif %}

        <!-- <button type="submit" class="button button-primary p-1 px-4 mt-6 ml-auto">{% trans "Update Password" %}</button> -->
    </form>
</div>

<script>
    // Function to check if all fields are filled
    function checkForm() {
        const saveButton = document.getElementById('saveButton');
        const oldPassword = document.getElementById('id_old_password').value;
        const newPassword1 = document.querySelector('input[name="new_password1"]').value;
        const newPassword2 = document.querySelector('input[name="new_password2"]').value;

        // Enable the button if all fields are filled, otherwise disable it
        if (oldPassword && newPassword1 && newPassword2) {
            saveButton.classList.remove('button-disabled');
            saveButton.removeAttribute('disabled');
        } else {
            saveButton.classList.add('button-disabled');
            saveButton.setAttribute('disabled', 'true');
        }
    }

    // Attach the checkForm function to the input event for all inputs in the form
    document.addEventListener('DOMContentLoaded', function() {
        const form = document.getElementById('changePasswordForm');
        const inputs = form.querySelectorAll('input');

        // Listen for input events on all form fields
        inputs.forEach(input => {
            input.addEventListener('input', checkForm);
        });

        // Initial check in case fields are already filled when the page loads
        checkForm();
    });
</script>

{% endblock %}

apps/users/templates/password.html
{% extends 'layouts/form_layout.html' %}

{% block title %}Change Password{% endblock %}
{% block buttons %}
    <button onclick=" document.getElementById('changePasswordForm').submit()" id="saveButton" class="button button-primary button-disabled" type="submit">Update Password</button>
    <a href="{% url 'settings' %}" class="button">Cancel</a>
{% endblock %}

{% block form_content %}
<div class="flex flex-col h-full items-center justify-center">
    <form class="max-w-[520px]" id="changePasswordForm" action="{% url 'profile-password-change' %}" method="post">
        {% csrf_token %}
        <!-- <i class="material-symbols-outlined text-5xl">key</i> -->
        <!-- Current Password -->
        <div class="flex items-center gap-4">
            <h1 class="w-60 text-right">Current Password</h1>
            <input id="id_old_password" type="password" name="old_password" class="input" autofocus required>
        </div>
        <div class="h-6 flex items-center justify-end">
            {% if form.old_password.errors %}
                <p class="text-red-500 text-xs">{{ form.old_password.errors.0 }}</p>
            {% endif %}
        </div>

        <!-- New Password -->
        <div class="flex items-center gap-4">
            <h1 class="w-60 text-right">New Password</h1>
            <input type="password" name="new_password1" class="input" required>
        </div>
        <div class="h-6 flex items-center justify-end">
            {% if form.new_password1.errors %}
                <p class="text-red-500 text-xs">{{ form.new_password1.errors.0 }}</p>
            {% endif %}
        </div>


        <!-- Confirm Password -->
        <div class="flex items-center gap-4">
            <h1 class="w-60 text-right">Confirm Password</h1>
            <input type="password" name="new_password2" class="input" required>
        </div>
        <div class="h-6 flex items-center justify-end">
            {% if form.new_password2.errors %}
                <p class="text-red-500 text-xs">{{ form.new_password2.errors.0 }}</p>
            {% endif %}
        </div>

        <!-- <button type="submit" class="button button-primary p-1 px-4 mt-6 ml-auto">Update Password</button> -->
    </form>
</div>

<script>
    // Function to check if all fields are filled
    function checkForm() {
        const saveButton = document.getElementById('saveButton');
        const oldPassword = document.getElementById('id_old_password').value;
        const newPassword1 = document.querySelector('input[name="new_password1"]').value;
        const newPassword2 = document.querySelector('input[name="new_password2"]').value;

        // Enable the button if all fields are filled, otherwise disable it
        if (oldPassword && newPassword1 && newPassword2) {
            saveButton.classList.remove('button-disabled');
            saveButton.removeAttribute('disabled');
        } else {
            saveButton.classList.add('button-disabled');
            saveButton.setAttribute('disabled', 'true');
        }
    }

    // Attach the checkForm function to the input event for all inputs in the form
    document.addEventListener('DOMContentLoaded', function() {
        const form = document.getElementById('changePasswordForm');
        const inputs = form.querySelectorAll('input');

        // Listen for input events on all form fields
        inputs.forEach(input => {
            input.addEventListener('input', checkForm);
        });

        // Initial check in case fields are already filled when the page loads
        checkForm();
    });
</script>


{% endblock %}

apps/users/templates/profile.html
{% extends 'layouts/form_layout.html' %}
{% load i18n %}

{% block form_content %}
    <div class="relative flex gap-4">
        <img class="avatar" src="{{ profile.avatarDisplay }}" />
        <div>
            <h1 class="text-2xl">{{ profile.fullName }}</h1>
            <h1 class="font-light opacity-70">@{{ profile.user.username }}</h1>
            <p class="opacity-70">{{ profile.bio|linebreaksbr }}</p>
        </div>
        <a href="{% url 'profile-edit' %}" class="absolute top-0 right-0 button">{% trans "Edit Profile" %}</a>
    </div>

    <div class="custom-border-b my-6"></div>

    <div class="flex flex-col gap-2 opacity-70">
        <h1 class="flex gap-2">
            <i class="material-symbols-outlined text">mail</i>
            {{ profile.user.email }}
        </h1>

        {% if profile.birthday %}
        <h1 class="flex gap-2">
            <i class="material-symbols-outlined">calendar_today</i>
            {{ profile.birthday }}
        </h1>
        {% endif %}

        {% if profile.phone_number %}
        <h1 class="flex gap-2">
            <i class="material-symbols-outlined">call</i>
            {{ profile.phone_number }}
        </h1>
        {% endif %}
    </div>

    <div class="custom-border-b my-6"></div>
{% endblock %}

apps/users/templates/profile_edit.html
{% extends 'layouts/form_layout.html' %}
{% load i18n %}

{% block form_label %}{% trans "Edit Profile" %}{% endblock %}

{% block form_buttons %}
{% endblock %}

{% block form_content %}

<form id="profileForm" action="{% url 'profile-edit' %}" method="POST" enctype="multipart/form-data"
    class="flex flex-col gap-2 items-center">
    {% csrf_token %}
    <input type="hidden" name="form_type" value="profile_details">
    
    <!-- Profile Avatar Upload -->
    <div class="relative">
        <label for="{{ profile_form.avatar.id_for_label }}" class="cursor-pointer">
            <div class="overflow-hidden rounded-full">
                <img id="avatarPreview" class="avatar" src="{{ user.profile.avatarDisplay }}" />
                <div class="w-20 h-20 rounded-full absolute inset-0 bg-black bg-opacity-30 flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity">
                    <i class="material-symbols-outlined">edit</i>
                </div>
            </div>
        </label>
        <input type="file" id="avatarInput" accept="image/*" name="avatar" class="hidden">
    </div>

    <div class="input-container bg-transparent border-none">
        <label for="id_gender" class="text-xs font-semibold">{% trans "Username" %}</label> 
        <div class="text-lg font-light">
            {{ user.username }}
        </div>
    </div>

    <div class="input-container bg-transparent border-none">
        <label for="id_gender" class="text-xs font-semibold">{% trans "Email" %}</label>
        <div class="flex justify-between items-center text-lg">
            <div class="flex gap-2 items-center">
                <div class="font-light">
                    {{ user.email }}
                </div>
                {% if request.user.emailaddress_set.first.verified %}
                    <i class="material-symbols-outlined text-green-500">check</i>
                {% else %}
                    <i class="material-symbols-outlined  text-yellow-500">error</i>
                {% endif %}
            </div>
            <div class="flex gap-3">
                {% if not request.user.emailaddress_set.first.verified %}
                <a href="#" class="text-yellow-500 text-sm hover:underline" onclick="document.getElementById('verifyEmailForm').submit();">{% trans "Verify" %}</a>
                {% endif %}
                <a href="#" class="text-blue-500 text-sm hover:underline" onclick="openEmailModal()">{% trans "Change" %}</a>
            </div>
        </div>
    </div>

    <div class="flex gap-2 w-full">
        <div class="input-container">
            <label for="id_first_name" class="text-xs font-semibold">{% trans "First Name" %}</label>
            {{ user_form.first_name }}
            <script>
                document.getElementById('{{ user_form.first_name.id_for_label }}').addEventListener('input', function(e) {
                    e.target.value = e.target.value.charAt(0).toUpperCase() + e.target.value.slice(1);
                });
            </script>
        </div>
        <div class="input-container">
            <label for="id_last_name" class="text-xs font-semibold">{% trans "Last Name" %}</label>
            {{ user_form.last_name }}
            <script>
                document.getElementById('{{ user_form.last_name.id_for_label }}').addEventListener('input', function(e) {
                    e.target.value = e.target.value.charAt(0).toUpperCase() + e.target.value.slice(1);
                });
            </script>
        </div>
    </div>
    
    <div class="input-container">
        <label for="id_gender" class="text-xs font-semibold">{% trans "Phone Number" %}</label>
        {{ profile_form.phone_number }}
    </div>

    <!-- Gender -->
    <div class="input-container">
        <label for="id_gender" class="text-xs font-semibold">{% trans "Gender" %}</label>
        {{ profile_form.gender }}
    </div>

    <!-- Birthday -->
    <div class="input-container">
        <label for="id_gender" class="text-xs font-semibold">{% trans "Birthday (m/d/y)" %}</label>
        {{ profile_form.birthday }}
    </div>

    <!-- Bio -->
    <div class="input-container">
        <label for="id_gender" class="text-xs font-semibold">{% trans "Bio" %}</label>
        {{ profile_form.bio }}
    </div>
    <div class="flex gap-2 items-center mt-2 ml-auto">
        <button id="saveButton" class="button button-primary button-disabled w-20" type="submit">{% trans "Save" %}</button>
        <a href="{% url 'profile' %}" class="button w-20">{% trans "Cancel" %}</a>
    </div>
</form>

<form id="verifyEmailForm" action="{% url 'profile-email-verify' %}" method="post" class="hidden">
    {% csrf_token %}
</form>

{% include 'modals/change_email_modal.html' %}


<script>
    // Add event listener to detect changes in the form
    document.getElementById('profileForm').addEventListener('input', function() {
        document.getElementById('saveButton').classList.remove('button-disabled');
    });

    const avatarInput = document.getElementById('avatarInput');
    const avatarPreview = document.getElementById("avatarPreview");
    avatarInput.addEventListener("change", function (event) {
        const file = event.target.files[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = function (e) {
                avatarPreview.src = e.target.result;
            };
            reader.readAsDataURL(file);
        }
    });
</script>
{% endblock %}